/**
 * @Author: ningshaohui
 * @Date: 2023-02-09 18:21:51
 * @LastEditTime: 2023-02-09 18:21:06
 * @LastEditors: ningshaohui
 * @Description:
 * @
 */

#ifndef _OTA_MANAGER_COMMON_H_
#define _OTA_MANAGER_COMMON_H_

typedef void (* UpdateStatusCb) (bool isEnd, int progress);

#define MAX_FILE_PATH_LENGTH (256U)
#define OTA_CLOUD_URL_HEAD "https://mqtt.zhito.com:9443"


enum class OtaManagerEventID {
    OTA_MANAGER_EVENT_NONE,
    OTA_MANAGER_EVENT_TRANSFER_REQUEST,
    OTA_MANAGER_EVENT_TRANSFER_START,
    OTA_MANAGER_EVENT_TRANSFER_FAILED,
    OTA_MANAGER_EVENT_TRANSFER_SUCCESS,
    OTA_MANAGER_EVENT_DOWNLOAD_REQUEST,
    OTA_MANAGER_EVENT_DOWNLOAD_START,
    OTA_MANAGER_EVENT_DOWNLOAD_FAILED,
    OTA_MANAGER_EVENT_DOWNLOAD_SUCCESS,
    OTA_MANAGER_EVENT_PARSE_VERIFY_FAILED,
    OTA_MANAGER_EVENT_PARSE_VERIFY_SUCCESS,
    OTA_MANAGER_EVENT_PRE_CONDITION_NOT_MEET,
    OTA_MANAGER_EVENT_PRE_CONDITION_MEET,
    OTA_MANAGER_EVENT_UPDATE_FAILED,
    OTA_MANAGER_EVENT_UPDATE_SUCCESS,
    OTA_MANAGER_EVENT_CHECK_UPDATE_RESULT_FAILED,
    OTA_MANAGER_EVENT_CHECK_UPDATE_RESULT_SUCCESS,
    OTA_MANAGER_EVENT_UPLOAD_RESULT_FAILED,
    OTA_MANAGER_EVENT_UPLOAD_RESULT_SUCCESS
};

enum class OtaManagerMainState{
    OTA_MANAGER_MAIN_STATE_IDLE = 0,
    OTA_MANAGER_MAIN_STATE_PREPARE_DOWNLOAD,
    OTA_MANAGER_MAIN_STATE_DOWNLOAD,
    OTA_MANAGER_MAIN_STATE_PARSE_AND_VERIFY,
    OTA_MANAGER_MAIN_STATE_UPDATE,
    OTA_MANAGER_MAIN_STATE_CHECK_RESULT,
    OTA_MANAGER_MAIN_STATE_UPLOAD_RESULT,
    OTA_MANAGER_MAIN_STATE_MAX
};

enum class OtaManagerSubState{
    OTA_MANAGER_SUB_STATE_NONE = 0,
    OTA_MANAGER_SUB_STATE_CHECK_RESULT_REBOOT,
    OTA_MANAGER_SUB_STATE_CHECK_RESULT_VERSION
};

enum class OtaManagerModuleID{
    OTA_MANAGER_MAIN,
    OTA_MANAGER_PREPARE_TRANSFER,
    OTA_MANAGER_TRANSFER,
    OTA_MANAGER_PARSE_VERIFY,
    OTA_MANAGER_PREPARE_RECEIVE,
    OTA_MANAGER_RECEIVE,
    OTA_MANAGER_UPDATE,
    OTA_MANAGER_CHECK_RESULT,
    OTA_MANAGER_UPLOAD_RESULT,
};

enum class OtaManagerResult{
    OTA_MANAGER_SUCCESS = 0,
    OTA_MANAGER_FAILED 
};

enum class OtaUpdateResultCode {
    OTA_UPDATE_RESULT_SUCCESS,
    OTA_UPDATE_RESULT_ERROR
};

#endif//_OTA_MANAGER_COMMON_H_